# Site Settings
title: Start Jekyll
email: rdz.gabb@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/project-local"
url: "https://Gabbrdz.github.io"
twitter_username: Gabbrdz
github_username:  Gabbrdz
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM