# Site Settings
title:  Gabriela Rodriguez
email: rdz.gabb@gmail.com
description: >
  Gabriela Rodriguez Designer & Illustrator
baseurl: ""
url: "https://127.0.0.1:4000/"
twitter_username: Gabbrdz
github_username:  Gabbrdz
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM